language: python

python:
  - "3.5"

before_install:
  - chmod +x install-nltk-resources.py
  - chmod +x green_magic/tests/weedmaster_test.py

install:
  - pip install .
 
script:
  - python install-nltk-resources.py
  - python green_magic/tests/weedmaster_test.py
